import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Pagination, Navigation } from 'swiper';
import styles from '../styles/Landing.module.css';
import style from '../styles/style.module.css';
import imgSection1 from '../public/images/section1Landing.jpg';
import imgSection2 from '../public/images/section2Landing.jpg';
import imgSection3 from '../public/images/section3Landing.jpg';
import Bluecheckbox from '../public/icon/bluecheckbox.svg';
import Yellowcheckbox from '../public/icon/yellowcheckbox.svg';
import Navbar from '../components/navbarLanding';

import UserOpini from '../public/images/useropinion.jpg';
import UserOpini2 from '../public/images/useropinion2.jpg';
import UserOpini3 from '../public/images/useropinion3.jpg';
import logo from '../public/logo.svg';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';

function Landingpage() {
  return (
    <>
      <Head>
        <title>Landingpage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={`container-fluid ${styles.container}`}>
        <div className={`row ${styles}`}>
          <section className={`row ${styles.section1}`}>
            <div className="col-1" />
            {/* ---------Left---------- */}
            <div className={`col-5 ${styles.divLeft1}`}>
              <div className={`row ${styles.mainLeft1}`}>
                <div className={styles.title1}>
                  <h3>Talenta terbaik negri untuk perubahan revolusi 4.0</h3>
                </div>
                <div className={styles.loream1}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui, consequuntur, alias debitis nisi fuga voluptas.</div>
                <div className={`${styles}`}>
                  <Link href="/login">
                    <button className={styles.buttonSearch}>
                      <div>Mulai Dari Sekarang</div>
                    </button>
                  </Link>
                </div>
              </div>
            </div>
            {/* -----------------Right--------------- */}
            <div className={`col-5 ${styles.divRight1}`}>
              <div className={styles.mainRigh1}>
                <div className={styles.background1} />
                <div className={styles.divImage1}>
                  <Image className={styles.image1} src={imgSection1} width={500} height={430} />
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section2------------------------ */}
          <section className={`row ${styles.section2}`}>
            <div className="col-1" />
            {/* -------left------ */}
            <div className={`col-5 ${styles.section2Responsive}`}>
              <div className={styles.mainRigh1}>
                {/* <div className={styles.divSquare}></div> */}
                <div className={styles.background2} />
                <div className={styles.divImage2}>
                  <Image className={styles.image2} src={imgSection2} width={400} height={320} />
                </div>
              </div>
            </div>

            {/* ------Right------- */}
            <div className={`col-5 ${styles.divLeft1}`}>
              <div className="row">
                <div className={styles.title2}>
                  <h3 style={{ fontWeight: '600', fontSize: '34px' }}>Kenapa harus mencari tallent di peworld</h3>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src={Bluecheckbox} width={15} height={15} />
                  </div>
                  <div style={{ fontWeight: '400', color: '#46505C' }}>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src={Bluecheckbox} width={15} height={15} />
                  </div>
                  <div style={{ fontWeight: '400', color: '#46505C' }}>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src={Bluecheckbox} width={15} height={15} />
                  </div>
                  <div style={{ fontWeight: '400', color: '#46505C' }}>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src={Bluecheckbox} width={15} height={15} />
                  </div>
                  <div style={{ fontWeight: '400', color: '#46505C' }}>Lorem ipsum dolor sit amet.</div>
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section3------------------------ */}
          <section className={`row ${styles.section3}`}>
            <div className="col-1" />
            {/* -------left------ */}
            <div className={`col-5 ${styles.leftContent3}`}>
              <div className={styles.divTitle3}>
                <h3 style={{ fontWeight: '600', fontSize: '34px' }}>Skill Tallent</h3>
              </div>
              <div className={styles.divLorem} style={{ fontWeight: '400', color: '#46505C' }}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.
              </div>
              <div className={styles.divList3}>
                <div style={{ marginRight: '100px' }}>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>Java</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>Kotlin</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>PHP</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>Javascript</div>
                  </div>
                </div>
                <div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>Golang</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>C++</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>Ruby</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src={Yellowcheckbox} width={15} height={15} />
                    </div>
                    <div style={{ fontWeight: '400', color: '#46505C' }}>10+ Bahasa Lainnya</div>
                  </div>
                </div>
              </div>
            </div>

            {/* ------Right------- */}
            <div className={`col-5 ${styles.section3Responsive}`}>
              <div className={styles.mainRigh1}>
                {/* <div className={styles.divSquare}></div> */}
                <div className={styles.background3} />
                <div className={styles.divImage3}>
                  <Image className={styles.image3} src={imgSection3} width={470} height={330} />
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section4------------------------ */}
          <section className={`row ${styles.section4}`}>
            <div className="col-1" />
            {/* -------main------ */}
            <div className="col-10">
              <div className={styles.title4}>
                <h3 style={{ fontWeight: '600', fontSize: '36px' }}>Their opinion about peworld</h3>
              </div>
              <div className={styles.divCardUser}>
                <Swiper
                  slidesPerView={3}
                  spaceBetween={50}
                  slidesPerGroup={3}
                  loop
                  loopFillGroupWithBlank
                  pagination={{
                    clickable: true,
                  }}
                  navigation
                  modules={[Pagination, Navigation]}
                  className="mySwiper"
                >
                  <SwiperSlide>
                    <div className={`card d-flex align-items-center ms-5 ${styles.responsiveCardSwiper}`} style={{ width: '18rem' }}>
                      <div style={{ marginTop: '10%' }}>
                        <Image src={UserOpini} width={100} height={100} style={{ borderRadius: '100%', border: '6px solid #FBB017 ' }} />
                      </div>
                      <div className="card-body d-flex flex-column align-items-center">
                        <h5 className="card-title">Harry Styles</h5>
                        <h6 style={{ color: '#9EA0A5' }}>Web Developer</h6>
                        <p className="card-text" style={{ marginLeft: '10%', fontSize: '15px', textAlign: 'center', color: '#46505C' }}>
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.
                        </p>
                      </div>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className={`card d-flex align-items-center ms-4 ${styles.responsiveCardSwiper}`} style={{ width: '18rem' }}>
                      <div style={{ marginTop: '10%' }}>
                        <Image src={UserOpini2} width={100} height={100} style={{ borderRadius: '100%', border: '6px solid #FBB017' }} />
                      </div>
                      <div className="card-body d-flex flex-column align-items-center">
                        <h5 className="card-title">Niall Horan</h5>
                        <h6 style={{ color: '#9EA0A5' }}>Web Developer</h6>
                        <p className="card-text" style={{ marginLeft: '10%', fontSize: '15px', textAlign: 'center', color: '#46505C' }}>
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.
                        </p>
                      </div>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className={`card d-flex align-items-center ${styles.responsiveCardSwiper}`} style={{ width: '18rem' }}>
                      <div style={{ marginTop: '10%' }}>
                        <Image src={UserOpini3} width={100} height={100} style={{ borderRadius: '100%', border: '6px solid #FBB017' }} />
                      </div>
                      <div className="card-body d-flex flex-column align-items-center">
                        <h5 className="card-title">Louis Tomlinson</h5>
                        <h6 style={{ color: '#9EA0A5' }}>Web Developer</h6>
                        <p className="card-text" style={{ marginLeft: '10%', fontSize: '15px', textAlign: 'center', color: '#46505C' }}>
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.
                        </p>
                      </div>
                    </div>
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section------------------------ */}
          <section className="row">
            <div className="col-1" />
            <div className="col-10 ">
              <div
                style={{
                  backgroundColor: '#5E50A1',
                  minHeight: '200px',
                  paddingTop: '6%',
                  borderTopLeftRadius: '50px',
                  borderBottomLeftRadius: '5px',
                  borderBottomRightRadius: '50px',
                  borderTopRightRadius: '5px',
                  marginTop: '50px',
                }}
                className="container "
              >
                <div className={styles.invitation}>
                  <div className="d-block d-md-flex justify-content-between ">
                    <h3 style={{ maxWidth: '300px', color: 'white', fontWeight: '600', fontSize: '36px', marginLeft: '3rem' }}>
                      Lorem ipsum <br /> dolor sit amet.
                    </h3>
                    <br />
                    <div className="d-flex align-items-center">
                      <button className="btn bg-light py-3 me-4" style={{ color: '#796EAF', fontWeight: '700' }}>
                        Mulai Dari Sekarang
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        <footer className={` ${style.footer} mt-5`}>
          <Image className="mb-3" src={logo} alt="logo" />
          <br></br>
          <p className="d-inline-block w-50">Bersama memajukan bangsa dalam mengembangkan sumber daya manusia yang berkualitas.</p>
          <hr style={{ borderTop: '2px solid white' }} />
          <div className="d-flex justify-content-between">
            <p>2020 Pewworld. All right reserved</p>
            <div className="d-flex justify-content-end">
              <p>Telepon</p>
              <p style={{ marginLeft: '15px' }}>Email</p>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}

export default Landingpage;
